test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -25,10 +25,8 @@ jobs:
       uses: gradle/gradle-build-action@v2
       with:
         arguments: test
-    - name: branch name
-      id: branch_name
+    - name: Test failure
       run: |
-        echo "name=${{ github.head_ref }}"
-        FULL_REF="${{ github.event.merge_group.head_ref }}"
-        BRANCH_NAME="${FULL_REF##*/}"
-        echo "Extracted branch name: '$BRANCH_NAME'"
+        echo "This step is designed to always fail"
+        exit 1
+        
